#statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 1001310000
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgresql.database }}
            - name: POSTGRESQL_USER
              value: {{ .Values.postgresql.user }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/pgsql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes:
          - {{ .Values.storage.accessMode }}
        resources:
          requests:
            storage: {{ .Values.storage.size }}
        volumeName: {{ .Values.storage.volumeName }}